apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-dokumentarkiv
  namespace: min-side
  labels:
    team: min-side
spec:
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  tokenx:
    enabled: true
  image: {{ image }}
  port: 3000
  liveness:
    path: /dokumentarkiv/api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /dokumentarkiv/api/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /dokumentarkiv/api/internal/metrics
  replicas:
    min: 2
    max: 4
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
  ingresses:
    - "https://www.ansatt.dev.nav.no/dokumentarkiv"
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi
